name: Android Plugins CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: build plugins
      run: bash build_plugins.sh

    - name: print list tree
      run: ls -R build


    #签名开始

    #签名li
    - uses: noriban/sign-android-release@v3
      name: Sign li app APK
      # ID used to access action output
      id: sign_li_app
      with:
        releaseDirectory: build/li
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "33.0.1"
    #签名yue
    - uses: noriban/sign-android-release@v3
      name: Sign yue app APK
      # ID used to access action output
      id: sign_yue_app
      with:
        releaseDirectory: build/yue
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "33.0.1"

    #签名结束

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: |
          ${{steps.sign_li_app.outputs.signedReleaseFile}}
          ${{steps.sign_yue_app.outputs.signedReleaseFile}}
          build/yue-html/*.zip
